import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import Breadcrumbs from "../Breadcrumbs";
import SiteHeader from "../SiteHeader";
import SiteFooter from "../SiteFooter";

export const metadata:Metadata={title:"Guías para cuidar tu ropa | Aquabon",description:"Consejos prácticos sobre lavado, manchas, tejidos, acolchados, zapatillas y cuidado de prendas.",alternates:{canonical:"/blog"},openGraph:{title:"Guías para cuidar tu ropa | Aquabon",description:"Consejos prácticos para lavar, secar y cuidar tus prendas.",url:"/blog",type:"website",locale:"es_AR"}};

const guides=[
  {title:"Cómo limpiar un tapado sin dañarlo",description:"Cómo revisar etiqueta, forro y estructura; cuidados entre usos, lavado permitido y señales para consultar antes de mojarlo.",href:"/blog/como-limpiar-un-tapado-sin-danarlo",cluster:"TAPADOS",date:"22 SEP",image:"/blog/revisar-tapado-etiqueta-forro.webp",alt:"Revisión del forro y etiqueta de un tapado azul con cepillo y percha a mano"},
  {title:"¿Qué prendas conviene llevar a la tintorería?",description:"Una guía para decidir qué hacer con sacos, tapados, vestidos y prendas con forro o adornos según su etiqueta y construcción.",href:"/blog/que-prendas-conviene-llevar-a-la-tintoreria",cluster:"TINTORERÍA",date:"21 SEP",image:"/blog/revisar-prendas-tintoreria.webp",alt:"Revisión de etiqueta y forro de un saco antes de enviarlo a tintorería"},
  {title:"¿Cuál es la diferencia entre lavandería y tintorería?",description:"Qué servicio elegir según la etiqueta, el tejido, la estructura de la prenda y el tipo de cuidado profesional.",href:"/blog/diferencia-entre-lavanderia-y-tintoreria",cluster:"CUIDADO DE ROPA",date:"20 SEP",image:"/blog/elegir-lavanderia-o-tintoreria.webp",alt:"Ropa cotidiana y prendas estructuradas clasificadas por separado"},
  {title:"Cómo sacar el olor a humedad de un acolchado",description:"Cómo diferenciar olor a encierro, humedad interna y moho, y qué hacer en cada caso sin dañar el relleno.",href:"/blog/como-sacar-olor-a-humedad-de-un-acolchado",cluster:"ACOLCHADOS",date:"19 SEP",image:"/blog/comprobar-humedad-acolchado.webp",alt:"Comprobación de humedad en el relleno de un acolchado"},
  {title:"¿Cada cuánto hay que lavar un acolchado?",description:"Una frecuencia práctica según funda, uso, mascotas, manchas, relleno y señales de suciedad.",href:"/blog/cada-cuanto-lavar-un-acolchado",cluster:"ACOLCHADOS",date:"18 SEP",image:"/blog/revisar-cuando-lavar-acolchado.webp",alt:"Revisión de una mancha y el relleno de un acolchado"},
  {title:"Cómo secar un acolchado sin que quede húmedo o apelmazado",description:"Secadora o aire libre: cómo elegir el método, redistribuir el relleno y comprobar la humedad interior.",href:"/blog/como-secar-un-acolchado",cluster:"ACOLCHADOS",date:"17 SEP",image:"/blog/comprobar-secado-acolchado.webp",alt:"Revisión del relleno de un acolchado durante el secado"},
  {title:"Símbolos de lavado de un acolchado: cómo leer la etiqueta",description:"Una guía visual para entender lavado, blanqueo, secado, planchado y cuidado profesional.",href:"/blog/simbolos-de-lavado-de-un-acolchado",cluster:"ACOLCHADOS",date:"16 SEP",image:"/blog/leer-etiqueta-acolchado.webp",alt:"Etiqueta de cuidado de un acolchado azul"},
  {title:"¿Cómo lavar un acolchado de plumas sin dañarlo?",description:"Qué revisar antes, cómo saber si entra en tu lavarropas y por qué el secado es la etapa decisiva.",href:"/blog/como-lavar-un-acolchado-de-plumas",cluster:"ACOLCHADOS",date:"15 SEP",image:"/blog/revisar-etiqueta-acolchado-plumas.webp",alt:"Revisión de un acolchado de plumas antes del lavado"}
];

export default function BlogPage(){return <main className="blog-index"><SiteHeader event="whatsapp_blog_index"/><Breadcrumbs items={[{label:"Inicio",href:"/"},{label:"Guías",href:"/blog"}]}/><header className="blog-index-hero"><div><p className="eyebrow">GUÍAS AQUABON</p><h1>Guías para cuidar tu ropa</h1><p>Consejos claros sobre lavado, manchas, tejidos, acolchados, zapatillas y prendas especiales. Para saber qué podés resolver en casa y cuándo conviene pedir ayuda.</p></div><div className="blog-index-mark" aria-hidden="true"><span>AQ</span><i/><i/><i/></div></header><section className="featured-guides"><div className="blog-section-heading"><p className="eyebrow">TODAS LAS GUÍAS</p><h2>Consejos prácticos, tema por tema</h2></div><div className="guide-list">{guides.map(g=><Link className="guide-card" href={g.href} key={g.href}><Image src={g.image} alt={g.alt} width={700} height={467} sizes="(max-width: 760px) 100vw, 50vw"/><div><span>{g.cluster} · {g.date}</span><h3>{g.title}</h3><p>{g.description}</p><i>LEER GUÍA ↗</i></div></Link>)}</div></section><section className="guide-clusters"><p className="eyebrow">TEMAS</p><h2>Encontrá el cuidado que necesitás</h2><div>{["Acolchados","Tintorería","Zapatillas","Manchas","Cuidado de ropa","Lavado"].map((x,i)=><article key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3><p>Nuevas guías prácticas durante septiembre.</p></article>)}</div></section><section className="blog-service-link"><div><p className="eyebrow">¿NECESITÁS QUE LO HAGAMOS POR VOS?</p><h2>Conocé los servicios de Aquabon</h2></div><Link href="/servicios">Ver todos los servicios ↗</Link></section><SiteFooter/></main>}
