import type { Metadata } from "next";
import SeoLanding, { landingMetadata, type LandingData } from "./SeoLanding";
const specs:Record<string,{h1:string;intro:string;event:string;message:string;items:LandingData["items"];faqs:LandingData["faqs"]}> = {
 airbnb:{h1:"Lavandería de sábanas y ropa blanca para Airbnb en Mar del Plata",intro:"Coordinación de sábanas, fundas, toallas y ropa blanca para recambios entre huéspedes.",event:"whatsapp_airbnb",message:"Hola Aquabon, quería consultar por el servicio de lavandería para un alojamiento.",items:[{title:"Ropa blanca",copy:"Sábanas, fundas y toallas sujetas a revisión de volumen."},{title:"Recambios",copy:"Coordinamos frecuencia y tiempos según la operación del alojamiento."},{title:"Retiro y entrega",copy:"Se consulta según zona, volumen y disponibilidad."}],faqs:[{question:"¿Trabajan con alquileres temporarios?",answer:"Sí, evaluamos cada operación según volumen y frecuencia."},{question:"¿Pueden coordinar recambios?",answer:"Definimos la coordinación antes de comenzar."},{question:"¿Hay mínimo de prendas?",answer:"Consultanos con el volumen estimado."},{question:"¿Retiran y entregan?",answer:"Según zona y disponibilidad."}]},
 hoteles:{h1:"Servicio de lavandería para hoteles y alojamientos en Mar del Plata",intro:"Soluciones para ropa blanca, sábanas y toallas con frecuencia y volumen acordados.",event:"whatsapp_hoteles",message:"Hola Aquabon, quería consultar por lavandería para un hotel o alojamiento.",items:[{title:"Ropa blanca",copy:"Evaluamos sábanas, fundas y toallas según composición y uso."},{title:"Recurrencia",copy:"Acordamos una frecuencia compatible con el volumen."},{title:"Coordinación",copy:"Definimos recepción, seguimiento y entrega."}],faqs:[{question:"¿Aceptan servicios recurrentes?",answer:"Sí, después de evaluar volumen y frecuencia."},{question:"¿Trabajan grandes volúmenes?",answer:"Confirmamos capacidad y plazos antes de aceptar."},{question:"¿Incluye retiro?",answer:"Se cotiza según zona y disponibilidad."},{question:"¿Cómo solicito una propuesta?",answer:"Escribinos por WhatsApp con cantidad y frecuencia."}]},
 restaurantes:{h1:"Lavandería para restaurantes y gastronomía en Mar del Plata",intro:"Evaluamos manteles, servilletas, delantales, uniformes y textiles de trabajo para un servicio periódico.",event:"whatsapp_restaurantes",message:"Hola Aquabon, quería consultar por lavandería para un negocio gastronómico.",items:[{title:"Textiles de mesa",copy:"Manteles y servilletas según tejido y tipo de uso."},{title:"Ropa de trabajo",copy:"Delantales y uniformes sujetos a valoración."},{title:"Frecuencia",copy:"Coordinamos un esquema según volumen y necesidad."}],faqs:[{question:"¿Lavan manteles?",answer:"Evaluamos el tejido, las manchas y el volumen."},{question:"¿Reciben uniformes?",answer:"Sí, sujeto a revisión del material y la operación."},{question:"¿Garantizan todas las manchas?",answer:"No; depende de su origen y antigüedad."},{question:"¿Pueden retirar?",answer:"Consultanos según zona y disponibilidad."}]},
 deportes:{h1:"Lavado de ropa y uniformes deportivos en Mar del Plata",intro:"Servicio a medida para equipos de fútbol, básquet, hockey, rugby, gimnasios, academias y clubes.",event:"whatsapp_deportes",message:"Hola Aquabon, quería consultar por el lavado de ropa de un equipo deportivo.",items:[{title:"Equipaciones",copy:"Valoramos camisetas, shorts y otras prendas de entrenamiento."},{title:"Volumen",copy:"Definimos capacidad y frecuencia antes de comenzar."},{title:"Seguimiento",copy:"Coordinamos recepción y aviso por WhatsApp."}],faqs:[{question:"¿Trabajan con clubes?",answer:"Evaluamos clubes, equipos, gimnasios y academias."},{question:"¿Hay servicio recurrente?",answer:"Puede coordinarse según volumen y frecuencia."},{question:"¿Aceptan distintos deportes?",answer:"Sí; importa más el tejido y el volumen que la disciplina."},{question:"¿Retiran la ropa?",answer:"Según zona y disponibilidad."}]}
};
export function businessData(kind:keyof typeof specs):LandingData{const s=specs[kind];const path=kind==="deportes"?"/empresas/lavado-ropa-deportiva":"/empresas/lavanderia-"+kind;return {path,title:s.h1+" | Aquabon",description:s.intro,eyebrow:"SOLUCIONES PARA EMPRESAS",h1:s.h1,intro:s.intro,event:s.event,message:s.message,cta:"Consultar servicio",crumbs:[{label:"Inicio",href:"/"},{label:"Empresas",href:"/empresas"},{label:s.h1.split(" en Mar del Plata")[0],href:path}],sections:[{heading:"Un servicio ajustado a tu operación",text:"Antes de comenzar confirmamos textiles, volumen, frecuencia, capacidad y logística. Así evitamos promesas que no se adapten a tu negocio."}],items:s.items,steps:[{title:"Contanos tu operación",copy:"Indicá tipo de textiles, cantidad y frecuencia."},{title:"Evaluamos capacidad",copy:"Revisamos necesidades y disponibilidad."},{title:"Coordinamos",copy:"Acordamos una forma de trabajo clara."}],faqs:s.faqs,related:[{label:"Servicios para empresas",href:"/empresas"},{label:"Todos los servicios",href:"/servicios"}]};}
export {landingMetadata,SeoLanding};
